CREATE OR REPLACE PROCEDURE SP_PRODUCT_REPORT(P_CATEGORY VARCHAR DEFAULT NULL)
RETURNS TABLE (PRODUCT_NAME VARCHAR, CATEGORY VARCHAR, PRICE NUMBER(10,2), STOCK_QUANTITY INT, IS_ACTIVE BOOLEAN)
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python')
IMPORTS = ('@{{ git_repository }}/branches/{{ git_branch }}/snowflake/snowpark/RAW/QUICKBOOKS/SP_PAYMENT_SUMMARY/src/main.py')
HANDLER = 'main.run'
;