
CREATE OR REPLACE PROCEDURE SP_PAYMENT_SUMMARY(P_STATUS VARCHAR DEFAULT NULL)
RETURNS TABLE (PAYMENT_METHOD VARCHAR, TOTAL_AMOUNT NUMBER(12,2), TRANSACTION_COUNT INT)
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python')
IMPORTS = ('@{{ git_repository }}/branches/{{ git_branch }}/snowflake/snowpark/RAW/QUICKBOOKS/SP_PAYMENT_SUMMARY/src/main.py')
HANDLER = 'main.run'
;