CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATE DEFAULT CURRENT_DATE(),
    TOTAL_AMOUNT NUMBER(12,2),
    STATUS VARCHAR(20) DEFAULT 'PENDING'
);