CREATE OR REPLACE PROCEDURE SUMMARIZE_CUSTOMER_ORDERS(MIN_ORDER_COUNT INT)
RETURNS TABLE(CUSTOMER_ID INT, FULL_NAME VARCHAR, ORDER_COUNT INT, TOTAL_SPENT NUMBER(12,2))
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python')
IMPORTS = (
    '@{{ git_repository }}/branches/{{ git_branch }}/snowflake/snowpark/RAW/HUBSPOT/SP_SUMMARIZE_CUSTOMER_ORDERS/src/main.py'
)
HANDLER = 'main.run';