CREATE OR REPLACE TABLE PAYMENTS (
    PAYMENT_ID INT AUTOINCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PAYMENT_METHOD VARCHAR(50) NOT NULL,
    AMOUNT NUMBER(12,2) NOT NULL,
    PAYMENT_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS VARCHAR(20) DEFAULT 'COMPLETED'
);